### ISSUE TITLE
Dockerfile: About the alpine image

### ISSUE THREAD

**Issue by leonkappes** [zekroTJA/voidseeker#53]
I looked at commit 7ba7e9c706ff92c1aaed5bd00f30345183a12c68:
The package you tried to install is only on the [edge repository](https://pkgs.alpinelinux.org/package/edge/testing/x86/libgdiplus).
You can use this packages with the [repository flag](https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management#Add_a_Package), your command would then be the following: 
`apk add libgdiplus --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted`

**Comment by zekroTJA** [comment]
Oh well, that's nice. 

Actually, I wondered why I used buster for the backend image, tried alpine with .NET 5 and reverted back because I got frustrated that the package was not found. :D

Thank you. ^^
